[project]
name = "surveyjs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.18.0",
    "joblib>=1.5.1",
    "orjson>=3.10.18",
    "pydantic>=2.11.5",
    "typer>=0.16.0",
]
